### ISSUE TITLE
Support Ruby 2.0 / 2.1 / 2.2

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus-ruby-client#29]
As Ruby 1.9 is officially retired, we need to migrate to Ruby 2.0 or later.

I confirmed that all unit tests and integration_test works fine with Ruby 2.0.0-p598, 2.1.5 and 2.2.0.

* We should add Ruby version matrix test to the CI.
* Update the website to announce Ruby 2.0-2.2 support.

Any other considerations / TODOs?

**Comment by kmaehashi** [comment]
As Ubuntu 12.04 / 14.04 still has Ruby 1.9 package, I don't want to drop support for Ruby 1.9.

**Comment by kumagi** [comment]
:+1:

**Comment by kmaehashi** [comment]
We now confirmed that Jubatus Ruby Client works with Ruby 2.0 or later!

http://ci.jubat.us/job/jubatus-ruby-client/
